TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS BELOW HERE

# Install databases
DB += bpmrffe.db

DB += $(ASYN)/db/asynRecord.db
DB += $(AUTOSAVE)/asApp/Db/save_restoreStatus.db

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD EXTRA GNUMAKE RULES BELOW HERE
