version: "3.2"
services:
    rffe-ioc: &base
        image: ghcr.io/lnls-dig/rffe-epics-ioc
        network_mode: host
        restart: unless-stopped
        volumes:
          - type: bind
            source: /var/opt/rffe-epics-ioc
            target: /var/opt/rffe-epics-ioc
        environment: &env
            CRATE_NUMBER: ${CRATE_NUMBER}
            RFFE_BASE_IP_ADDRESS: 192.168.2.190
    rffe-ioc-1:
        <<: *base
        environment:
            <<: *env
            BPM_NUMBER: 1
    rffe-ioc-2:
        <<: *base
        environment:
            <<: *env
            BPM_NUMBER: 2
    rffe-ioc-3:
        <<: *base
        environment:
            <<: *env
            BPM_NUMBER: 3
    rffe-ioc-4:
        <<: *base
        environment:
            <<: *env
            BPM_NUMBER: 4
    rffe-ioc-5:
        <<: *base
        environment:
            <<: *env
            BPM_NUMBER: 5
    rffe-ioc-6:
        <<: *base
        environment:
            <<: *env
            BPM_NUMBER: 6
    rffe-ioc-7:
        <<: *base
        environment:
            <<: *env
            BPM_NUMBER: 7
    rffe-ioc-8:
        <<: *base
        environment:
            <<: *env
            BPM_NUMBER: 8
    rffe-ioc-9:
        <<: *base
        environment:
            <<: *env
            BPM_NUMBER: 9
    rffe-ioc-10:
        <<: *base
        environment:
            <<: *env
            BPM_NUMBER: 10
    rffe-ioc-11:
        <<: *base
        environment:
            <<: *env
            BPM_NUMBER: 11
    rffe-ioc-12:
        <<: *base
        environment:
            <<: *env
            BPM_NUMBER: 12
    rffe-ioc-13:
        <<: *base
        environment:
            <<: *env
            BPM_NUMBER: 13
    rffe-ioc-14:
        <<: *base
        environment:
            <<: *env
            BPM_NUMBER: 14
    rffe-ioc-15:
        <<: *base
        environment:
            <<: *env
            BPM_NUMBER: 15
    rffe-ioc-16:
        <<: *base
        environment:
            <<: *env
            BPM_NUMBER: 16
    rffe-ioc-17:
        <<: *base
        environment:
            <<: *env
            BPM_NUMBER: 17
    rffe-ioc-18:
        <<: *base
        environment:
            <<: *env
            BPM_NUMBER: 18
    rffe-ioc-19:
        <<: *base
        environment:
            <<: *env
            BPM_NUMBER: 19
    rffe-ioc-20:
        <<: *base
        environment:
            <<: *env
            BPM_NUMBER: 20
    rffe-ioc-21:
        <<: *base
        environment:
            <<: *env
            BPM_NUMBER: 21
    rffe-ioc-22:
        <<: *base
        environment:
            <<: *env
            BPM_NUMBER: 22
    rffe-ioc-23:
        <<: *base
        environment:
            <<: *env
            BPM_NUMBER: 23
    rffe-ioc-24:
        <<: *base
        environment:
            <<: *env
            BPM_NUMBER: 24
